### ISSUE TITLE
安装了运行不起来

### ISSUE THREAD

**Issue by potato09** [talkincode/ToughRADIUS#110]
[root@USER ~]# radiusd
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 938, in emit
    self.stream = self._open()
  File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/toughradius/info.log'
Logged from file radiusd.py, line 54
[2018-06-12 16:51:06 toughradius.common.radiusd-2356] [INFO] <RudiusAuthServer fileno=6 address=0.0.0.0:1812>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 938, in emit
    self.stream = self._open()
  File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/toughradius/info.log'
Logged from file radiusd.py, line 60
[2018-06-12 16:51:06 toughradius.common.radiusd-2356] [INFO] <RudiusAcctServer fileno=7 address=0.0.0.0:1813>

**Comment by potato09** [comment]
centos OS 7

**Comment by jamiesun** [comment]
请使用最新版6.x
