### ISSUE TITLE
小压力，随机测试，导致java进程cpu占用100%

### ISSUE THREAD

**Issue by someonebw** [talkincode/ToughRADIUS#114]
1.测试工具
https://github.com/jamiesun/RadiusTester

并发200，随机测试。

测试文本中 //2000用户。

2.toughradius版本 6.1.1.3版本。
用户库测试用户100000个。
默认安装。
centos 7 ，8 core 8gmem

3.toughradius日志里面的错误，出现大量如下：
2019-07-18 03:43:29.572 TOUGHRADIUS [NioDatagramAcceptor-5] INFO  - UdpSession created (0x0000459B: nio datagram, server, /172.19.100.7:23923 => /0:0:0:0:0:0:0:0:1813)
2019-07-18 03:43:29.588 TOUGHRADIUS [NioDatagramAcceptor-4] INFO  - UdpSession created (0x0000459C: nio datagram, server, /172.19.100.7:23924 => /0:0:0:0:0:0:0:0:1812)

4.查看java进程中，挂起的线程。发现，没有占用cpu量，特别大的线程。
通过show-busy-java-threads脚本定位有问题的threads（https://github.com/oldratlee/useful-scripts）

############################################################################################################
[root@server222 useful-scripts]# ./show-busy-java-threads 11544
================================================================================
2019-07-18 03:56:56.160798855 [1/0]: ./show-busy-java-threads 11544
================================================================================

[1] Busy(13.7%) thread(11662/0x2d8e) stack of java process(11544) under user(root):
"authExecutorFilterPool-2-thread-5" #75 prio=5 os_prio=0 tid=0x00007f0bf002b000 nid=0x2d8e runnable [0x00007f0cb3cfb000]
   java.lang.Thread.State: RUNNABLE
	at org.toughradius.common.SpinLock.lock(SpinLock.java:10)
	at org.toughradius.component.OnlineCache.isLimitOver(OnlineCache.java:299)
	at org.toughradius.handler.RadiusBasicHandler.accessRequestReceived(RadiusBasicHandler.java:329)
	at org.toughradius.handler.RadiusAuthHandler.messageReceived(RadiusAuthHandler.java:88)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704)
	at java.lang.Thread.run(Thread.java:748)

[2] Busy(13.7%) thread(11664/0x2d90) stack of java process(11544) under user(root):
"acctExecutorFilterPool-3-thread-1" #76 prio=5 os_prio=0 tid=0x00007f0c50003000 nid=0x2d90 runnable [0x00007f0cb39f9000]
   java.lang.Thread.State: RUNNABLE
	at org.toughradius.common.SpinLock.lock(SpinLock.java:10)
	at org.toughradius.component.OnlineCache.putOnline(OnlineCache.java:258)
	at org.toughradius.handler.RadiusAccountingFilter.addOnline(RadiusAccountingFilter.java:125)
	at org.toughradius.handler.RadiusAccountingFilter.doStart(RadiusAccountingFilter.java:134)
	at org.toughradius.handler.RadiusAccountingFilter.doFilter(RadiusAccountingFilter.java:55)
	at org.toughradius.handler.RadiusBasicHandler.accountingRequestReceived(RadiusBasicHandler.java:386)
	at org.toughradius.handler.RadiusAcctHandler.messageReceived(RadiusAcctHandler.java:63)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704)
	at java.lang.Thread.run(Thread.java:748)

[3] Busy(13.7%) thread(11675/0x2d9b) stack of java process(11544) under user(root):
"acctExecutorFilterPool-3-thread-4" #84 prio=5 os_prio=0 tid=0x00007f0c50006800 nid=0x2d9b runnable [0x00007f0cb31f1000]
   java.lang.Thread.State: RUNNABLE
	at org.toughradius.common.SpinLock.lock(SpinLock.java:10)
	at org.toughradius.component.OnlineCache.putOnline(OnlineCache.java:258)
	at org.toughradius.handler.RadiusAccountingFilter.addOnline(RadiusAccountingFilter.java:125)
	at org.toughradius.handler.RadiusAccountingFilter.doStart(RadiusAccountingFilter.java:134)
	at org.toughradius.handler.RadiusAccountingFilter.doFilter(RadiusAccountingFilter.java:55)
	at org.toughradius.handler.RadiusBasicHandler.accountingRequestReceived(RadiusBasicHandler.java:386)
	at org.toughradius.handler.RadiusAcctHandler.messageReceived(RadiusAcctHandler.java:63)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704)
	at java.lang.Thread.run(Thread.java:748)

[4] Busy(13.7%) thread(11687/0x2da7) stack of java process(11544) under user(root):
"acctExecutorFilterPool-3-thread-16" #96 prio=5 os_prio=0 tid=0x00007f0c5001c000 nid=0x2da7 runnable [0x00007f0cb21c5000]
   java.lang.Thread.State: RUNNABLE
	at org.toughradius.common.SpinLock.lock(SpinLock.java:10)
	at org.toughradius.component.OnlineCache.putOnline(OnlineCache.java:258)
	at org.toughradius.handler.RadiusAccountingFilter.addOnline(RadiusAccountingFilter.java:125)
	at org.toughradius.handler.RadiusAccountingFilter.doStart(RadiusAccountingFilter.java:134)
	at org.toughradius.handler.RadiusAccountingFilter.doFilter(RadiusAccountingFilter.java:55)
	at org.toughradius.handler.RadiusBasicHandler.accountingRequestReceived(RadiusBasicHandler.java:386)
	at org.toughradius.handler.RadiusAcctHandler.messageReceived(RadiusAcctHandler.java:63)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704)
	at java.lang.Thread.run(Thread.java:748)

[5] Busy(13.7%) thread(11689/0x2da9) stack of java process(11544) under user(root):
"acctExecutorFilterPool-3-thread-18" #98 prio=5 os_prio=0 tid=0x00007f0c50020000 nid=0x2da9 runnable [0x00007f0cb1fc3000]
   java.lang.Thread.State: RUNNABLE
	at org.toughradius.common.SpinLock.lock(SpinLock.java:10)
	at org.toughradius.component.OnlineCache.putOnline(OnlineCache.java:258)
	at org.toughradius.handler.RadiusAccountingFilter.addOnline(RadiusAccountingFilter.java:125)
	at org.toughradius.handler.RadiusAccountingFilter.doStart(RadiusAccountingFilter.java:134)
	at org.toughradius.handler.RadiusAccountingFilter.doFilter(RadiusAccountingFilter.java:55)
	at org.toughradius.handler.RadiusBasicHandler.accountingRequestReceived(RadiusBasicHandler.java:386)
	at org.toughradius.handler.RadiusAcctHandler.messageReceived(RadiusAcctHandler.java:63)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704)
	at java.lang.Thread.run(Thread.java:748)
############################################################################################################

**Comment by jamiesun** [comment]
这个测试工具并发200的量并不是每秒200个请求，这个工具是使用python+gevent开发的，使用了异步模式，随机测试不建议用来做性能测试，因为超时问题引起无限重发。

**Comment by jamiesun** [comment]
已修复, 由于使用java自旋锁导致, 自旋锁不应该使用在不确定耗时的任务中
