### ISSUE TITLE
API处理错误

### ISSUE THREAD

**Issue by fillorkill** [talkincode/ToughRADIUS#94]
为了看见详细错误，我将product.py里的try catch移除，以下是移除后的错误日志

Uncaught exception
[Failure instance: Traceback: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 388-391: ordinal not in range(128)
/opt/toughradius/venv/lib/python2.7/site-packages/cyclone/web.py:1067:_execute
/opt/toughradius/venv/lib/python2.7/site-packages/twisted/internet/defer.py:306:addCallbacks
/opt/toughradius/venv/lib/python2.7/site-packages/twisted/internet/defer.py:588:_runCallbacks
/opt/toughradius/venv/lib/python2.7/site-packages/cyclone/web.py:1102:_execute_handler
--- <exception caught here> ---
/opt/toughradius/venv/lib/python2.7/site-packages/cyclone/web.py:1073:_deferred_handler
/opt/toughradius/toughradius/manage/api/v1/api_product.py:39:post
/opt/toughradius/toughradius/manage/api/apibase.py:58:render_success
/opt/toughradius/toughradius/manage/api/apibase.py:20:render_result
/opt/toughradius/venv/lib/python2.7/site-packages/toughlib/apiutils.py:67:make_message
/opt/toughradius/venv/lib/python2.7/site-packages/toughlib/apiutils.py:39:make_sign
]
HTTPRequest(protocol='http', host='127.0.0.1:1816', method='POST', uri='/api/v1/product/query', version='HTTP/1.1', remote_ip='127.0.0.1', body='nonce=1462725957.51&sign=2BE08AA1F83F2833B2C387A2F0280BEE', headers={'Content-Length': '57', 'Accept-Encoding': 'identity', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'close', 'Host': '127.0.0.1:1816', 'User-Agent': 'Python-urllib/2.7'})
Traceback (most recent call last):
  File "/opt/toughradius/toughradius/manage/base.py", line 56, in get_error_html
    return self.render_string("error.html", msg=u"500:服务器处理失败，请联系管理员")
  File "/opt/toughradius/toughradius/manage/base.py", line 92, in render_string
    template_vars["permit"] = self.current_user.permit
  File "/opt/toughradius/venv/lib/python2.7/site-packages/cyclone/util.py", line 47, in __getattr__
    raise AttributeError(name)
AttributeError: permit
Uncaught exception in write_error: permit
[http] 500 POST /api/v1/product/query (127.0.0.1) 5.78ms

**Comment by fillorkill** [comment]
这是有try catch的错误码
[api debug] :: /api/v1/customer/auth response body: {"msg": "ApiStatus(code=99999, desc='unknow error', msg=u'\\u672a\\u77e5\\u9519\\u8bef'), ", "nonce": "1462727430", "code": 99999, "sign": "542972A8C897BA85C2739D4077638EA0"}

**Comment by fillorkill** [comment]
已解决
修改toughlib/apiutils.py
第39行print 'sign params:',strs
修改为print 'sign params:',strs.encode('utf-8')
